title: vrCAVE Operation Guide
description: vrCAVE setup and operation documentation
theme: just-the-docs

plugins:
  - jekyll-default-layout
  
url: https://triggerhappyned.github.io/NewOpsGuide

aux_links:
  Template Repository: https://github.com/triggerhappyned/NewOpsGuide

